;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GASTags.Event.Player.Abilities.Attack",NewTagName="GASTags.Events.Player.Abilities.Attack")
+GameplayTagRedirects=(OldTagName="GASTags.Event.Player.Abilities",NewTagName="GASTags.Events.Player.Abilities")
+GameplayTagRedirects=(OldTagName="GASTags.Event.Player",NewTagName="GASTags.Events.Player")
+GameplayTagRedirects=(OldTagName="GASTags.Event",NewTagName="GASTags.Events")
+GameplayTagList=(Tag="GameplayCue.HitReach",DevComment="")
+GameplayTagList=(Tag="GASTags.CDSKILL",DevComment="")
+GameplayTagList=(Tag="GASTags.Events.Enemy.Death",DevComment="")
+GameplayTagList=(Tag="GASTags.Events.Player.Abilities.Attack",DevComment="玩家角色攻击能力标签")
+GameplayTagList=(Tag="GASTags.Events.Player.Skill",DevComment="")
+GameplayTagList=(Tag="GASTags.GASAbilities.Enemy.HitReact",DevComment="受击能力标签")
+GameplayTagList=(Tag="GASTags.SetByCaller.Melee",DevComment="")
+GameplayTagList=(Tag="GASTags.SetByCaller.PlayerSkill",DevComment="")
+GameplayTagList=(Tag="GASTags.Status.Dead",DevComment="")

